# yaml-language-server: $schema=https://json.schemastore.org/stylelintrc.json
# explicitly setting schema since using non-standard filename
#───────────────────────────────────────────────────────────────────────────────
# DOCS https://stylelint.io/user-guide/rules
#───────────────────────────────────────────────────────────────────────────────
plugins:
  - stylelint-scss
  - stylelint-order
  - stylelint-declaration-block-no-ignored-properties
extends:
  #- stylelint-config-recommended
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-recommended-scss
rules:
  scss/at-rule-no-unknown: true
  scss/at-if-no-null: true
  scss/at-if-closing-brace-space-after: always-intermediate
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/selector-no-redundant-nesting-selector: null
  scss/no-duplicate-mixins: true
  scss/no-duplicate-dollar-variables: null
  alpha-value-notation: number
  annotation-no-unknown: true
  at-rule-no-unknown: null
  at-rule-empty-line-before:
    - always
    - except:
        - after-same-name
        - blockless-after-same-name-blockless
        - first-nested
    - ignore:
        - inside-block
  block-no-empty: true
  color-function-notation:
    - legacy
    - ignore:
        - with-var-inside
  color-no-invalid-hex: true
  comment-no-empty: true
  color-function-alias-notation: with-alpha
  comment-empty-line-before:
    - null
    - ignore:
        - after-comment
    - ignoreComments:
        - "/^#region/"
        - "/^#endregion/"
        - "/^[=-]*/"
  comment-whitespace-inside: null # always
  custom-property-empty-line-before: never
  custom-property-no-missing-var-function: true
  custom-media-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - {}
  custom-property-pattern:
    - ^((--)?[a-z][a-z0-9]*)(-{1,2}[a-z0-9]+)*$
    - {}
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-single-line-max-declarations: 2
  declaration-empty-line-before: never
  declaration-block-no-duplicate-custom-properties: true
  font-family-no-missing-generic-family-keyword: null
  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-syntaxes
  declaration-block-no-shorthand-property-overrides: true
  media-feature-name-no-unknown: true
  media-query-no-invalid: true
  named-grid-areas-no-invalid: true
  no-descending-specificity: null # not useful for themes
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: null
  no-empty-source: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  no-irregular-whitespace: true
  font-family-name-quotes: always-where-required  # always-where-recommended
  font-family-no-duplicate-names: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-name-case: null
  function-no-unknown: null
  function-url-quotes: always
  import-notation: url
  keyframe-block-no-duplicate-selectors: true
  keyframe-declaration-no-important: true
  keyframe-selector-notation: percentage-unless-within-keyword-only-block
  keyframes-name-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - {}
  media-feature-name-no-vendor-prefix: true
  rule-empty-line-before: null
  selector-anb-no-unmatchable: true
  selector-attribute-quotes: never
  selector-class-pattern: null # class names usually not defined by me
  selector-id-pattern: null # id names usually not defined by me
  selector-no-vendor-prefix: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  property-no-unknown: null
  property-no-vendor-prefix: null
  unit-no-unknown: true
  order/order:
    - custom-properties
    - declarations
  order/properties-order:
    - width
    - height
  plugin/declaration-block-no-ignored-properties: true
  value-keyword-case:
    - null
    - camelCaseSvgKeywords: true